version: "2.2"

services:

  frontend:
    build: 
      context: ./frontend 
    ports:
     - "3000:3000"
    container_name: frontend-con
    volumes: 
      - /var/lib/docker/volumes/our-vol/_data
    network : hackphaistus
    restart: always
    #environment:
    #stdin_open: true

  # mysql_db:
  #   image: mysql:8.0
  #   networks: app-tier
  #   volumes:
  #   ports:
  #    - "3306:3306"
  #   environment:
  #    - MYSQL_DATABASE=app 
  #    - MYSQL_USER= #채우기
  #    - MYSQL_PASSWORD= 
  #    - MYSQL_ROOT_PASSWORD=
  #   command: 

  backend:
    build:
      context: ./backend
    ports:
     - "5000:5000" 
    container_name: backend-con
    networks: 
     - hackphaistus
    volumes:
     - /var/lib/docker/volumes/backend/_data
    restart: always
    #command: gunicorn -w 1 -b 0.0.0.0:5000 --timeout=300 run:app
   

  rabbitmq:
    image : rabbitmq:3-management
    environment:
     - RABBITMQ_DEFAULT_USER= 2a22users
     - RABBITMQ_DEFAULT_PASS= hackphaistus
    ports:
     - "5672:5672"
     - "15672:15672"
    networks: 
     - hackphaistus
  #docker-compose 없이 사용할려면 #이미지설치 : docker pull rabbitmq:3-management
  #컨테이너 실행: docker run -d -p 15672:15672 -p 5672:5672 --name  msa-rabbitmq rabbitmq:3-management                                   


  db: # 서비스 명
    image: mysql # 사용할 이미지
    container_name: mysql-con # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/docker/volumes/mysql/_data # -v 옵션 (다렉토리 마운트 설정)


#docker-compose up -d

#network
# docker network : hackphaistus
# docker exec frontend-con ping backend-con

#volume
#docker volume prune
# sudo curl -L "https://github.com/docker/compose/releases/download/2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=dbof2a22162 --name mysql-con -v /var/lib/docker/volumes/mysql/_data mysql:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


# docker exec -it mysql-con bash

#mysql> CREATE USER '2a22'@'%' IDENTIFIED BY 'dbof2a22162';
# Query OK, 0 rows affected (0.00 sec)

# mysql> GRANT ALL PRIVILEGES ON *.* TO '2a22'@'%';
# Query OK, 0 rows affected (0.00 sec)

# mysql> flush privileges;
# Query OK, 0 rows affected (0.00 sec)

# mysql> quit